apiVersion: v1
kind: Service
metadata:
  name: luis-felipe-09-service
  namespace: luis-felipe-09-namespace
spec:
  type: NodePort
  ports:
  - port: 30001
    targetPort: 8087
    nodePort: 30001
  selector:
    app: luis-felipe-09-deployment
