apiVersion: apps/v1
kind: Deployment
metadata:
  name: luis-felipe-09-deployment
  namespace: luis-felipe-09-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luis-felipe-09-deployment
    template:
      metadata:
        labels:
          app: luis-felipe-09-deployment
    spec:
      containers:
      - name: luis-felipe-09-container
        image: luisfelipe1432/webflux-nosql
        imagePullPolicy: Always
        ports:
          - containerPort: 8087
        env:
        - name: DATABASE_NAME
          value: "elchino"
        - name: DATABASE_URI
          value: "mongodb://<MONGO_EC2_IP>:27017/elchino"
