apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: luis-felipe-09-namespace
  labels:
    app: mongo
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongo
