apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: luis-felipe-09-namespace
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: luisfelipe1432/frontend-nosql:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
          env:
            - name: API_PROXY_TARGET
              value: "http://54.221.239.210:30001"