apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: luis-felipe-09-namespace
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: luisfelipe1432/frontend-nosql
          imagePullPolicy: Always
          ports:
            - containerPort: 5173  # Ajustado al puerto por defecto de Vite